name: Lint

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'

jobs:
  clang-format:
    name: Run clang-format - `${{ matrix.path }}`
    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      matrix:
        path:
          - 'lib'
          - 'include'
          - 'firmware'
          - 'examples'
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Add LLVM repository
        run: |
          sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-16 main"
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt update

      - name: Install clang-format
        run: sudo apt-get install -y clang-format-16

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
          clang_format_dir: ${{ matrix.path }}
          check_name: clang-format - `${{ matrix.path }}`
          continue_on_error: false
